export const USERNAME_REGEX = /^[a-zA-z]*$/;
export const USERNAME_ERROR_MESSAGE="Incorrect Username"
export const PASSWORD_ERROR_MESSAGE="Incorrect Password"
export const EMPTY_STRING=""
export const NETWORK_ERROR="Network Error"
export const LOADING="Loading"
export const USERNAME="username"
export const PASSWORD="password"
export const TYPE_TEXT="text"
export const TYPE_PASSWORD="password"
export const LOGO="logo"
export const PRIMARY="primary"
export const LOGIN="Login"
export const URL = "https://5ea1a14db9f5ca00166c1f27.mockapi.io/api/"

export const imageURL="https://cdn.zeplin.io/5d0afc9102b7fa56760995cc/assets/8b9ff190-f490-4211-b2dd-61f476cfeabd.svg"